sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t lukewelbourn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lukewelbourn/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env "
  bucket_name: "elasticbeanstalk-us-east-1-143120837968"
  bucket_path: "docker-react"
  on:
    branch: master
